import { mkdir, rm } from "node:fs/promises"
import { dirname, relative, resolve } from "node:path"
import { pathToFileURL } from "node:url"
import type { ElementType } from "react"

import { componentDocsConfig } from "../component-docs.config"
import type { ComponentDoc } from "../component-docs/schema"

type LoadedDoc = ComponentDoc<ElementType>
type LoadedManifest = { doc: LoadedDoc; path: string }

const root = resolve(import.meta.dirname, "..")
const storybookDirectory = resolve(root, ".generated/storybook")
const componentDirectory = resolve(
  root,
  componentDocsConfig.docs.componentDirectory
)
const generatedStoryDirectory = resolve(root, "app/.generated/fumadocs")
const registryPath = resolve(root, "registry.json")

function quote(value: unknown) {
  return JSON.stringify(value, null, 2)
}

function assertSerializable(value: unknown, location: string): void {
  if (value === undefined || value === null) return

  if (["string", "number", "boolean"].includes(typeof value)) return

  if (Array.isArray(value)) {
    value.forEach((item, index) =>
      assertSerializable(item, `${location}[${index}]`)
    )
    return
  }

  if (typeof value === "object") {
    const prototype = Object.getPrototypeOf(value)
    if (prototype !== Object.prototype && prototype !== null) {
      throw new Error(`${location} must be plain serializable data`)
    }

    Object.entries(value).forEach(([key, item]) =>
      assertSerializable(item, `${location}.${key}`)
    )
    return
  }

  throw new Error(`${location} contains unsupported ${typeof value} data`)
}

function exportName(id: string) {
  const value = id
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0]?.toUpperCase() + part.slice(1))
    .join("")

  if (!value)
    throw new Error(`Cannot create a story export from variant id "${id}"`)
  return /^\d/.test(value) ? `Story${value}` : value
}

function storyExportName(id: string) {
  return `${exportName(id)}Story`
}

function renderVariantSource(
  doc: LoadedDoc,
  variant: LoadedDoc["variants"][number]
) {
  const preview = doc.preview ?? doc.source
  const props = { ...variant.initial, ...variant.fixed }
  const componentName = `${exportName(variant.id)}Example`
  const importPath = `@/${preview.path
    .replace(/^app\//, "")
    .replace(/\.tsx$/, "")}`

  return `import { ${preview.exportName} } from ${quote(importPath)}

const props = ${quote(props)}

export default function ${componentName}() {
  return <${preview.exportName} {...props} />
}`
}

function generatedHeader() {
  return "// Generated by bun run generate. Do not edit.\n"
}

async function loadDocs() {
  const glob = new Bun.Glob("app/components/**/*.component.tsx")
  const manifests: LoadedManifest[] = []

  for await (const path of glob.scan({ cwd: root, onlyFiles: true })) {
    const url = `${pathToFileURL(resolve(root, path)).href}?generated=${Date.now()}`
    const module = (await import(url)) as { componentDoc?: LoadedDoc }
    if (!module.componentDoc)
      throw new Error(`${path} must export componentDoc`)
    manifests.push({ doc: module.componentDoc, path })
  }

  manifests.sort(
    (left, right) =>
      left.doc.docs.order - right.doc.docs.order ||
      left.doc.name.localeCompare(right.doc.name)
  )

  const names = new Set<string>()
  const slugs = new Set<string>()
  for (const { doc } of manifests) {
    if (names.has(doc.name))
      throw new Error(`Duplicate component name: ${doc.name}`)
    if (slugs.has(doc.docs.slug))
      throw new Error(`Duplicate documentation slug: ${doc.docs.slug}`)
    names.add(doc.name)
    slugs.add(doc.docs.slug)

    doc.variants.forEach((variant) => {
      assertSerializable(variant.initial, `${doc.name}.${variant.id}.initial`)
      assertSerializable(variant.fixed, `${doc.name}.${variant.id}.fixed`)
    })

    const variantIds = new Set(doc.variants.map((variant) => variant.id))
    for (const section of doc.docs.sections ?? []) {
      if (section.example && !variantIds.has(section.example)) {
        throw new Error(
          `${doc.name} section "${section.title}" references unknown example "${section.example}"`
        )
      }
      const variant = doc.variants.find(({ id }) => id === section.example)
      if (variant?.docs === false) {
        throw new Error(
          `${doc.name} section "${section.title}" references example "${section.example}" with docs disabled`
        )
      }
    }
  }

  return manifests
}

function renderStorybook(doc: LoadedDoc, manifestPath: string) {
  const manifestImport = relative(
    storybookDirectory,
    resolve(root, manifestPath)
  )
    .replaceAll("\\", "/")
    .replace(/^(?!\.)/, "./")
    .replace(/\.tsx$/, "")

  const stories = doc.variants
    .map((variant, index) => {
      const storybook = `componentDoc.variants[${index}].storybook`
      return `export const ${exportName(variant.id)}: Story = {
  name: ${quote(variant.title)},
  args: {
    ...componentDoc.variants[${index}].initial,
    ...componentDoc.variants[${index}].fixed,
  },
  parameters: ${storybook}?.parameters,
  play: ${storybook}?.play,
}`
    })
    .join("\n\n")

  return `${generatedHeader()}import type { Meta, StoryObj } from "@storybook/react-vite"

import { componentDoc } from ${quote(manifestImport)}

const meta = {
  component: componentDoc.component,
  tags: ["autodocs"],
  argTypes: componentDoc.controls,
  parameters: componentDoc.storybook?.parameters,
} satisfies Meta<typeof componentDoc.component>

export default meta
type Story = StoryObj<typeof meta>

${stories}
`
}

function renderFumadocsStory(doc: LoadedDoc, source: string) {
  const preview = doc.preview ?? doc.source
  const variants = doc.variants.filter((variant) => variant.docs !== false)

  if (variants.length === 0)
    throw new Error(`${doc.name} must expose at least one docs variant`)

  const stories = variants
    .map((variant, index) => {
      const storySource =
        index === 0 ? source.trim() : renderVariantSource(doc, variant)
      const filename =
        index === 0
          ? preview.path.split("/").at(-1)
          : `${doc.name}-${variant.id}.tsx`

      return `export const ${storyExportName(variant.id)} = defineStory({
  Component: ${preview.exportName},
  args: {
    initial: ${quote(variant.initial ?? {})},
    ${variant.fixed ? `fixed: ${quote(variant.fixed)},` : ""}
  },
  filename: ${quote(filename)},
  source: ${quote(storySource)},
})`
    })
    .join("\n\n")
  const primary = storyExportName(variants[0].id)

  return `${generatedHeader()}import { defineStory } from "@/lib/story"
import { ${preview.exportName} } from ${quote(`@/${preview.path.replace(/^app\//, "").replace(/\.tsx$/, "")}`)}

${stories}

export const story = ${primary}
`
}

function renderMdx(doc: LoadedDoc) {
  const pagePath = resolve(root, "content/docs", `${doc.docs.slug}.mdx`)
  const sourcePath = relative(
    dirname(pagePath),
    resolve(root, doc.source.path)
  ).replaceAll("\\", "/")
  const typePath = sourcePath.startsWith(".") ? sourcePath : `./${sourcePath}`
  const installAddress = `${componentDocsConfig.registry.githubAddress}/${doc.name}`
  const apiTables = [
    { title: doc.source.exportName, name: doc.source.propsType },
    ...(doc.source.additionalTypes ?? []),
  ]
    .map(
      ({ title, name }) =>
        `### ${title}\n\n<auto-type-table path=${quote(typePath)} name=${quote(name)} />`
    )
    .join("\n\n")
  const sections = (doc.docs.sections ?? [])
    .map(
      (section) =>
        `## ${section.title}\n\n${section.markdown}${
          section.example
            ? `\n\n<${storyExportName(section.example)}.WithPreview />`
            : ""
        }`
    )
    .join("\n\n")

  const exampleImports = [
    "story",
    ...new Set(
      (doc.docs.sections ?? []).flatMap((section) =>
        section.example ? [storyExportName(section.example)] : []
      )
    ),
  ].join(", ")

  return `---
title: ${doc.title}
description: ${doc.description}
---

import { ${exampleImports} } from "@/.generated/fumadocs/${doc.name}.story.tsx";

<story.WithPreview />

## Installation

\`\`\`sh
bunx --bun shadcn@latest add ${installAddress}
\`\`\`

## Usage

\`\`\`tsx
${doc.docs.usage}
\`\`\`

${sections}

## API

${apiTables}
`
}

async function writeGeneratedFiles(manifests: LoadedManifest[]) {
  const docs = manifests.map(({ doc }) => doc)
  await rm(storybookDirectory, { recursive: true, force: true })
  await rm(generatedStoryDirectory, { recursive: true, force: true })
  await rm(componentDirectory, { recursive: true, force: true })
  await mkdir(storybookDirectory, { recursive: true })
  await mkdir(generatedStoryDirectory, { recursive: true })
  await mkdir(componentDirectory, { recursive: true })

  for (const { doc, path: manifestPath } of manifests) {
    const mdxPath = resolve(root, "content/docs", `${doc.docs.slug}.mdx`)
    const preview = doc.preview ?? doc.source
    const previewSource = await Bun.file(resolve(root, preview.path)).text()
    await mkdir(dirname(mdxPath), { recursive: true })
    await Bun.write(
      resolve(storybookDirectory, `${doc.name}.stories.tsx`),
      renderStorybook(doc, manifestPath)
    )
    await Bun.write(
      resolve(generatedStoryDirectory, `${doc.name}.story.tsx`),
      renderFumadocsStory(doc, previewSource)
    )
    await Bun.write(mdxPath, renderMdx(doc))
  }

  await Bun.write(
    resolve(componentDirectory, "meta.json"),
    `${quote({ title: "Components", pages: docs.map((doc) => doc.docs.slug.replace(/^components\//, "")) })}\n`
  )

  await Bun.write(
    registryPath,
    `${quote({
      $schema: "https://ui.shadcn.com/schema/registry.json",
      name: componentDocsConfig.registry.name,
      homepage: componentDocsConfig.registry.homepage,
      items: docs.map((doc) => ({
        name: doc.name,
        type: doc.registry.type,
        title: doc.title,
        description: doc.description,
        ...(doc.registry.dependencies
          ? { dependencies: doc.registry.dependencies }
          : {}),
        ...(doc.registry.devDependencies
          ? { devDependencies: doc.registry.devDependencies }
          : {}),
        ...(doc.registry.registryDependencies
          ? { registryDependencies: doc.registry.registryDependencies }
          : {}),
        files: doc.registry.files,
      })),
    })}\n`
  )
}

const manifests = await loadDocs()
await writeGeneratedFiles(manifests)

if (Bun.argv.includes("--build-registry")) {
  const result = Bun.spawnSync(
    [
      "bunx",
      "--bun",
      "shadcn@latest",
      "build",
      "registry.json",
      "--output",
      "public/r",
    ],
    { cwd: root, stdout: "inherit", stderr: "inherit" }
  )
  if (result.exitCode !== 0) process.exit(result.exitCode)
}

console.log(
  `Generated documentation for ${manifests.length} component${manifests.length === 1 ? "" : "s"}.`
)
