import { mkdir, rm } from "node:fs/promises"
import { dirname, relative, resolve } from "node:path"
import { pathToFileURL } from "node:url"
import type { ElementType } from "react"

import { componentDocsConfig } from "../component-docs.config"
import type { ComponentDoc } from "../component-docs/schema"

type LoadedDoc = ComponentDoc<ElementType>

const root = resolve(import.meta.dirname, "..")
const storybookDirectory = resolve(root, ".generated/storybook")
const componentDirectory = resolve(
  root,
  componentDocsConfig.docs.componentDirectory
)
const generatedStoryDirectory = resolve(root, "app/.generated/fumadocs")
const legacyGeneratedStoryDirectory = resolve(componentDirectory, "_generated")
const registryPath = resolve(root, "registry.json")

function quote(value: unknown) {
  return JSON.stringify(value, null, 2)
}

function assertSerializable(value: unknown, location: string): void {
  if (value === undefined || value === null) return

  if (["string", "number", "boolean"].includes(typeof value)) return

  if (Array.isArray(value)) {
    value.forEach((item, index) =>
      assertSerializable(item, `${location}[${index}]`)
    )
    return
  }

  if (typeof value === "object") {
    const prototype = Object.getPrototypeOf(value)
    if (prototype !== Object.prototype && prototype !== null) {
      throw new Error(`${location} must be plain serializable data`)
    }

    Object.entries(value).forEach(([key, item]) =>
      assertSerializable(item, `${location}.${key}`)
    )
    return
  }

  throw new Error(`${location} contains unsupported ${typeof value} data`)
}

function exportName(id: string) {
  const value = id
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0]?.toUpperCase() + part.slice(1))
    .join("")

  if (!value)
    throw new Error(`Cannot create a story export from variant id "${id}"`)
  return /^\d/.test(value) ? `Story${value}` : value
}

function generatedHeader() {
  return "// Generated by bun run generate. Do not edit.\n"
}

async function loadDocs() {
  const glob = new Bun.Glob("app/components/**/*.component.tsx")
  const docs: LoadedDoc[] = []

  for await (const path of glob.scan({ cwd: root, onlyFiles: true })) {
    const url = `${pathToFileURL(resolve(root, path)).href}?generated=${Date.now()}`
    const module = (await import(url)) as { componentDoc?: LoadedDoc }
    if (!module.componentDoc)
      throw new Error(`${path} must export componentDoc`)
    docs.push(module.componentDoc)
  }

  docs.sort(
    (left, right) =>
      left.docs.order - right.docs.order || left.name.localeCompare(right.name)
  )

  const names = new Set<string>()
  const slugs = new Set<string>()
  for (const doc of docs) {
    if (names.has(doc.name))
      throw new Error(`Duplicate component name: ${doc.name}`)
    if (slugs.has(doc.docs.slug))
      throw new Error(`Duplicate documentation slug: ${doc.docs.slug}`)
    names.add(doc.name)
    slugs.add(doc.docs.slug)

    doc.variants.forEach((variant) => {
      assertSerializable(variant.initial, `${doc.name}.${variant.id}.initial`)
      assertSerializable(variant.fixed, `${doc.name}.${variant.id}.fixed`)
    })
  }

  return docs
}

function renderStorybook(doc: LoadedDoc, manifestPath: string) {
  const manifestImport = relative(
    storybookDirectory,
    resolve(root, manifestPath)
  )
    .replaceAll("\\", "/")
    .replace(/^(?!\.)/, "./")
    .replace(/\.tsx$/, "")

  const stories = doc.variants
    .map((variant, index) => {
      const storybook = `componentDoc.variants[${index}].storybook`
      return `export const ${exportName(variant.id)}: Story = {
  name: ${quote(variant.title)},
  args: {
    ...componentDoc.variants[${index}].initial,
    ...componentDoc.variants[${index}].fixed,
  },
  parameters: ${storybook}?.parameters,
  play: ${storybook}?.play,
}`
    })
    .join("\n\n")

  return `${generatedHeader()}import type { Meta, StoryObj } from "@storybook/react-vite"

import { componentDoc } from ${quote(manifestImport)}

const meta = {
  component: componentDoc.component,
  tags: ["autodocs"],
  argTypes: componentDoc.controls,
  parameters: componentDoc.storybook?.parameters,
} satisfies Meta<typeof componentDoc.component>

export default meta
type Story = StoryObj<typeof meta>

${stories}
`
}

function renderFumadocsStory(doc: LoadedDoc) {
  const variants = doc.variants
    .filter((variant) => variant.docs !== false)
    .map((variant) => ({
      variant: variant.title,
      initial: variant.initial ?? {},
      ...(variant.fixed ? { fixed: variant.fixed } : {}),
    }))

  if (variants.length === 0)
    throw new Error(`${doc.name} must expose at least one docs variant`)

  return `${generatedHeader()}import { defineStory } from "@/lib/story"
import { ${doc.source.exportName} } from ${quote(`@/${doc.source.path.replace(/^app\//, "").replace(/\.tsx$/, "")}`)}

export const story = defineStory({
  Component: ${doc.source.exportName},
  args: ${quote(variants)},
})
`
}

function renderMdx(doc: LoadedDoc) {
  const pagePath = resolve(root, "content/docs", `${doc.docs.slug}.mdx`)
  const sourcePath = relative(
    dirname(pagePath),
    resolve(root, doc.source.path)
  ).replaceAll("\\", "/")
  const typePath = sourcePath.startsWith(".") ? sourcePath : `./${sourcePath}`
  const installUrl = `${componentDocsConfig.registry.publicBaseUrl}/${doc.name}.json`
  const sections = (doc.docs.sections ?? [])
    .map((section) => `## ${section.title}\n\n${section.markdown}`)
    .join("\n\n")

  return `---
title: ${doc.title}
description: ${doc.description}
---

import { story } from "@/.generated/fumadocs/${doc.name}.story.tsx";

<story.WithControl />

## Installation

\`\`\`sh
bunx --bun shadcn@latest add ${installUrl}
\`\`\`

## Usage

\`\`\`tsx
${doc.docs.usage}
\`\`\`

## API

<auto-type-table path=${quote(typePath)} name=${quote(doc.source.propsType)} />

${sections}
`
}

async function writeGeneratedFiles(docs: LoadedDoc[]) {
  await rm(storybookDirectory, { recursive: true, force: true })
  await rm(generatedStoryDirectory, { recursive: true, force: true })
  await rm(legacyGeneratedStoryDirectory, { recursive: true, force: true })
  await mkdir(storybookDirectory, { recursive: true })
  await mkdir(generatedStoryDirectory, { recursive: true })

  const manifestGlob = new Bun.Glob("app/components/**/*.component.tsx")
  const manifests = new Map<string, string>()
  for await (const path of manifestGlob.scan({ cwd: root, onlyFiles: true })) {
    const module = (await import(
      `${pathToFileURL(resolve(root, path)).href}?mapping=${Date.now()}`
    )) as {
      componentDoc?: LoadedDoc
    }
    if (module.componentDoc) manifests.set(module.componentDoc.name, path)
  }

  for (const doc of docs) {
    const manifestPath = manifests.get(doc.name)
    if (!manifestPath)
      throw new Error(`Cannot find manifest path for ${doc.name}`)

    const mdxPath = resolve(root, "content/docs", `${doc.docs.slug}.mdx`)
    await mkdir(dirname(mdxPath), { recursive: true })
    await Bun.write(
      resolve(storybookDirectory, `${doc.name}.stories.tsx`),
      renderStorybook(doc, manifestPath)
    )
    await Bun.write(
      resolve(generatedStoryDirectory, `${doc.name}.story.tsx`),
      renderFumadocsStory(doc)
    )
    await Bun.write(mdxPath, renderMdx(doc))
  }

  await Bun.write(
    resolve(componentDirectory, "meta.json"),
    `${quote({ title: "Components", pages: docs.map((doc) => doc.docs.slug.replace(/^components\//, "")) })}\n`
  )

  await Bun.write(
    registryPath,
    `${quote({
      $schema: "https://ui.shadcn.com/schema/registry.json",
      name: componentDocsConfig.registry.name,
      homepage: componentDocsConfig.registry.homepage,
      items: docs.map((doc) => ({
        name: doc.name,
        type: doc.registry.type,
        title: doc.title,
        description: doc.description,
        ...(doc.registry.dependencies
          ? { dependencies: doc.registry.dependencies }
          : {}),
        ...(doc.registry.devDependencies
          ? { devDependencies: doc.registry.devDependencies }
          : {}),
        ...(doc.registry.registryDependencies
          ? { registryDependencies: doc.registry.registryDependencies }
          : {}),
        files: doc.registry.files,
      })),
    })}\n`
  )
}

const docs = await loadDocs()
await writeGeneratedFiles(docs)

if (Bun.argv.includes("--build-registry")) {
  const result = Bun.spawnSync(
    [
      "bunx",
      "--bun",
      "shadcn@latest",
      "build",
      "registry.json",
      "--output",
      "public/r",
    ],
    { cwd: root, stdout: "inherit", stderr: "inherit" }
  )
  if (result.exitCode !== 0) process.exit(result.exitCode)
}

console.log(
  `Generated documentation for ${docs.length} component${docs.length === 1 ? "" : "s"}.`
)
